import {I18nManager, StyleSheet} from 'react-native';
import scale from 'utilities/scale';

export default function SignStyle({colors}, height) {
    return StyleSheet.create({
        InputContainer: {
            alignSelf: 'center',
            marginTop: 20,
            width: '90%',
            flexDirection: 'row',
            alignItems: 'center',
        },
        CurrentInputBox: {
            minHeight: 44,
            flex: 1,
            borderRadius: 25,
        },
        container: {
            alignItems: 'center',
            height: '100%',
            marginBottom: '10%',
        },
        topImage: {
            resizeMode: 'contain',
            marginTop: 30,
        },
        wrap: {
            width: '100%',
            height: height,
        },
        subTitle: {
            width: '100%',
            fontSize: scale.font.xl,
            color: colors.textPrimary,
            marginBottom: 20,
            textAlign: 'center',
        },
        message: {
            width: '100%',
            fontSize: scale.font.s,
            color: colors.textPrimary,
            marginBottom: 20,
            textAlign: 'center',
        },
        PasswordBox: {
            minHeight: 44,
            width: '90%',
            alignSelf: 'center',
            marginTop: 20,
            borderRadius: 25,
        },
        InputBox: {
            paddingVertical: 5,
            borderWidth: 1,
            borderColor: colors.secondaryDark,
            backgroundColor: colors.surfaceDark,
            color: colors.textPrimaryDark,
            paddingHorizontal: 15,
            width: scale.ms(275, 0.3),
            alignSelf: 'center',
            marginTop: 15,
            alignItems: 'center',
            borderRadius: 15,
            fontSize: scale.font.xl,
            textAlign: I18nManager.isRTL ? 'right' : 'left',
        },
        InputPlainBox: {
            backgroundColor: colors.surfaceDark,
            color: colors.textPrimaryDark,
            paddingHorizontal: 15,
            width: scale.ms(275, 0.3),
            alignSelf: 'center',
            marginTop: 15,
            alignItems: 'center',
            fontSize: scale.font.xl,
            textAlign: I18nManager.isRTL ? 'right' : 'left',
        },
        otpBox: {
            height: 42,
            width: '60%',
            alignSelf: 'center',
            marginTop: 20,
            alignItems: 'center',
            borderColor: colors.secondaryDark,
        },
        otpItem: {
            width: 25,
            margin: 0,
            padding: 0,
            borderColor: colors.secondaryDark,
            color: colors.textPrimaryDark,
        },
        forgotPasswordText: {
            width: scale.ms(275, 0.3),
            marginVertical: 15,
            fontSize: scale.font.s,
            color: colors.textPrimary,
            textAlign: I18nManager.isRTL ? 'left' : 'right',
        },
        signupText: {
            marginTop: '5%',
            width: scale.ms(275, 0.3),
            borderRadius: 15,
            paddingVertical: 5,
        },
        loginLink: {
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            alignSelf: 'center',
            marginVertical: 40,
        },
        footerView: {
            alignItems: 'center',
            marginTop: 10,
        },
        footerText: {
            fontSize: scale.font.xl,
            color: colors.textPrimary,
            paddingHorizontal: 5,
        },
        footerLink: {
            color: colors.secondaryDark,
            fontSize: scale.font.xl,
        },
        popUpLink: {
            color: colors.link,
        },
        splitText: {
            fontSize: scale.font.xl,
            alignItems: 'center',
            color: colors.textPrimary,
        },
        lineStyle: {
            flex: 1,
            height: 1,
            borderWidth: 1,
            opacity: 1,
            padding: 0,
            alignSelf: 'center',
            borderColor: colors.primary,
            margin: 10,
        },
        lottie: {
            width: 100,
            height: 100,
        },
        socialContainer: {
            marginBottom: 15,
            flexDirection: 'column',
            alignContent: 'center',
            alignSelf: 'center',
            justifyContent: 'center',
        },
        flex: {flex: 1},
        socialButton: {
            alignSelf: 'center',
            width: 50,
            height: 50,
            resizeMode: 'contain',
        },

        popupTitle: {
            textAlign: 'left',
            width: '100%',
            paddingLeft: 10,
            fontSize: scale.font.xxxl,
            color: colors.secondaryDark,
        },
        InputBoxFull: {
            borderWidth: 1,
            paddingVertical: 5,
            paddingHorizontal: 15,
            margin: 10,
            borderColor: colors.secondaryDark,
            backgroundColor: colors.surfaceDark,
            color: colors.textPrimaryDark,
            width: scale.ms(275, 0.3),
            alignSelf: 'center',
            alignItems: 'center',
            borderRadius: 25,
            textAlign: I18nManager.isRTL ? 'right' : 'left',
        },
        InputPhoneBox: {
            backgroundColor: colors.surfaceDark,
            color: colors.textPrimaryDark,
            paddingHorizontal: 10,
            paddingVertical: 5,
            width: scale.ms(200, 0.2),
            alignSelf: 'center',
            alignItems: 'center',
            textAlign: I18nManager.isRTL ? 'right' : 'left',
        },
        popupContent: {
            width: scale.ms(275, 0.3),
            height: scale.ms(550, 0.3),
            alignSelf: 'center',
            alignContent: 'center',
            alignItems: 'center',
        },
        popupBody: {
            flex: 1,
            elevation: 10,
            alignSelf: 'center',
            alignContent: 'center',
            alignItems: 'center',
            backgroundColor: colors.surfaceDark,
            marginVertical: scale.ms(100, 0.3),
            marginHorizontal: scale.ms(50, 0.3),
            padding: 15,
        },
        phone_input: {
            flexDirection: 'row',
            alignItems: 'center',
            height: '100%',
            paddingLeft: 5,
            paddingRight: 2,
            marginRight: 5,
        },
        phone_input_view: {
            flexDirection: 'row',
            alignItems: 'center',
            overflow: 'hidden',
            width: scale.ms(275, 0.3),
        },
        phone_input_box: {
            flexDirection: 'row',
            alignItems: 'center',
            borderColor: colors.secondary,
            borderBottomWidth: 1,
            overflow: 'hidden',
            width: '100%',
        },
        popupActionButton: {flexDirection: 'row', marginRight: 10},
        iconContainerView: {marginVertical: 40, alignItems: 'center'},
        phone_check_box: {
            marginTop: '10%',
            width: scale.ms(275, 0.3),
        },
        referralCodeMessage: { width: scale.ms(275, 0.3)},
        socialButtonIcon: {width: 30, height: 30},
        buttonGap: {marginBottom: 10},
        phoneCode: {
            padding: 5,
            textAlignVertical: 'center',
            fontSize: scale.font.xl,
            color: colors.textPrimaryDark,
            height: '100%',
        },
    });
}
