export const appLogo = {
    full: require('./../assets/logos/logo_full.png'),
    min: require('./../assets/logos/logo_min.png'),
};

export const icons = {
    close: require('./../assets/icons/close.png'),
    retry: require('./../assets/icons/retry.png'),
    remove: require('./../assets/icons/remove.png'),
    download: require('./../assets/icons/download256.png'),
    pen: require('./../assets/icons/pen.png'),
    videoFail: require('./../assets/icons/videoFail.png'),
    about: require('./../assets/icons/about.png'),
    contactUs: require('./../assets/icons/contactUs.png'),
    archive: require('./../assets/icons/archive.png'),
    faq: require('./../assets/icons/faq.png'),
    changePassword: require('./../assets/icons/password.png'),
    contactus2: require('./../assets/icons/notebook-of-contacts.png'),
    notification: require('./../assets/icons/notification.png'),
    downArrow: require('./../assets/icons/down2.png'),
    unmute: require('./../assets/icons/mute.png'),
    mute: require('./../assets/icons/unmute.png'),
    blownUp: require('./../assets/icons/blownUp.png'),
};

export const lovitzIcons = {
    grey: require('./../assets/lovitzIcons/grey.png'),
    pink: require('./../assets/lovitzIcons/pink.png'),
    red: require('./../assets/lovitzIcons/red.png'),
    white: require('./../assets/lovitzIcons/white.png'),
};

export const fileIcons = {
    doc: require('./../assets/fileIcons/doc.png'),
    docx: require('./../assets/fileIcons/docx.png'),
    pdf: require('./../assets/fileIcons/pdf.png'),
    xls: require('./../assets/fileIcons/xls.png'),
    xlsx: require('./../assets/fileIcons/xlsx.png'),
    ppt: require('./../assets/fileIcons/ppt.png'),
    pptx: require('./../assets/fileIcons/pptx.png'),
    zip: require('./../assets/fileIcons/zip.png'),
    jpg: require('./../assets/fileIcons/jpg.png'),
    gif: require('./../assets/fileIcons/gif.png'),
    psd: require('./../assets/fileIcons/psd.png'),
    txt: require('./../assets/fileIcons/txt.png'),
    eps: require('./../assets/fileIcons/eps.png'),
    raw: require('./../assets/fileIcons/raw.png'),
    mp3: require('./../assets/fileIcons/mp3.png'),
};

export const placeHolders = {
    avatar: require('./../assets/images/default-avatar.jpg'),
    logo: require('./../assets/images/default-avatar2.png'),
    tempLogo: require('./../assets/images/tempSpaceLogo.png'),
    business: require('./../assets/images/businessImage.png'),
    user: require('./../assets/images/userImage.png'),
    noImage: require('../assets/images/placeholder.png'),
};

export const lottie = {
    splash: require('./../assets/lottie/splashLoader.json'),
    loader: require('./../assets/lottie/splashLoader.json'),
    finding_location: require('./../assets/lottie/finding_location.json'),
    empty: require('./../assets/lottie/empty.json'),
    common: require('./../assets/lottie/sk1.json'),
    startSearch: require('./../assets/lottie/startSearch.json'),
    searchEmpty: require('./../assets/lottie/searchEmpty.json'),
    no_notify: require('./../assets/lottie/no_notification.json'),
    lovitzLight: require('./../assets/lottie/lovitzLight.json'),
    lovitzDark: require('./../assets/lottie/lovitzDark.json'),
    rocketLight: require('./../assets/lottie/rocketLight.json'),
    rocketLightIos: require('./../assets/lottie/rocketLightIos.json'),
    rocketDark: require('./../assets/lottie/rocketDark.json'),
    rocketDarkIos: require('./../assets/lottie/rocketDarkIos.json'),
    ripple: require('./../assets/loaders/rippleLoader.json'),
};


export const clipBarIco = {
    camera: require('./../assets/clipBar/camera.png'),
    gallery: require('./../assets/clipBar/gallery.png'),
    video: require('./../assets/clipBar/video.png'),
    audio: require('./../assets/clipBar/audio.png'),
    files: require('./../assets/clipBar/attach.png'),
    delete: require('../assets/clipBar/delete.png'),
};

export const fonts = {
    Bahnschrift: 'Bahnschrift',
    ShadowsIntoLight: 'Caveat-Regular',
};

export const screens = {
    landingBG: require('../assets/screen/landing.jpg'),
    landing: require('../assets/screen/landingBG.png'),
    initializeHeader: require('../assets/screen/initializeHeader.png'),
    initializeHeaderDark: require('../assets/screen/initializeHeaderDark.png'),
    menuIcon: require('../assets/screen/menuIcon.png'),
    collabHeader: require('../assets/screen/collabHeader.png'),
    collabRocket: require('../assets/screen/collabRocket.png'),
    collabBG: require('../assets/screen/collabbg.png'),
    collabFooter: require('../assets/screen/collabFooter.png'),
    ideanGalleryDefaultAttach: require('../assets/screen/ideanGalleryDefaultAttach.png'),
    logo_wt: require('../assets/screen/logo_white.png'),
    facebook: require('../assets/screen/facebook.png'),
    google: require('../assets/screen/google.png'),
    apple: require('../assets/screen/apple.png'),
    co_space_ico: require('../assets/screen/clip_co_space.png'),
    collabSplash: require('../assets/screen/collab_splash.png'),
    collabSplashTextTop: require('../assets/screen/CsTop.png'),
    collabSplashMiddle: require('../assets/screen/CsMiddle.png'),
    collabSplashTextBottom: require('../assets/screen/CsBottom.png'),
    collabFlashTop: require('../assets/screen/collabFlashTop.png'),
    collabFlashMiddle: require('../assets/screen/collabFlashMiddle.png'),
    collabFlashBottom: require('../assets/screen/collabFlashBottom.png'),
    collabSplashBg: require('../assets/screen/collab_splash_bg.jpg'),
    coSpaceSplash: require('../assets/screen/coSpaceFlashText.png'),
    coSpaceSplashTextTop: require('../assets/screen/TsTop.png'),
    coSpaceSplashTextBottom: require('../assets/screen/TsBottom.png'),
    coSpaceSplashBg: require('../assets/screen/tempSplashBg.png'),
    coSpaceSplashBg2: require('../assets/screen/coSpaceBg2.jpg'),
    coSpaceSplashTextTop2: require('../assets/screen/tsT.png'),
    coSpaceSplashTextBottom2: require('../assets/screen/tsB.png'),
    coSpaceSplashBg3: require('../assets/screen/tsBg.png'),
    add: require('../assets/screen/add_clip.png'),
    emoji_ico: require('../assets/screen/emoji_ico.png'),
    lovitsWhite: require('../assets/screen/lovits_white.png'),
    flip_ico: require('../assets/screen/flip_ico.png'),
    search_ico: require('../assets/screen/search_ico.png'),
    search: require('../assets/screen/search.png'),
    threading: require('../assets/screen/threading.png'),
    titles: require('../assets/screen/titles.png'),
    badge_ico: require('../assets/screen/badge_ico.png'),
    lovits: require('../assets/screen/lovit.png'),
    lovits2: require('../assets/screen/lovit2.png'),
    lovitsGrey2: require('../assets/screen/lovitGrey2.png'),
    home: require('../assets/screen/home.png'),
    homeSolid: require('../assets/screen/homeSolid.png'),
    chat: require('../assets/screen/chatIcon.png'),
    chat2: require('../assets/screen/chatIcon3.png'),
    inviteIdean: require('../assets/screen/invite.png'),
    collabSpaceIco: require('../assets/screen/collab_space_ico.png'),
    clips: require('../assets/screen/clips.png'),
    insights: require('../assets/screen/insights.png'),
    collaber: require('../assets/screen/collaber.png'),
    collabing: require('../assets/screen/collabing.png'),
    invite: require('../assets/screen/inviteBlue.png'),
    general_user: require('../assets/screen/personal.png'),
    charity: require('../assets/screen/charity.png'),
    myInterest: require('../assets/screen/myInterest.png'),
    blank: require('../assets/screen/blank.png'),
    business: require('../assets/screen/bussiness.png'),
    attach: require('../assets/screen/attachIcon.png'),
    attach2: require('../assets/screen/ideanGalleryAdd.png'),
    rocket: require('../assets/screen/rocket.png'),
    rocketColor: require('../assets/screen/rocketColor.png'),
    personalClipEmpty: require('../assets/screen/personalClipPlaceholder.png'),
    invite_search: require('../assets/screen/invite_search.png'),
    collab_search: require('../assets/screen/collab_search.png'),
    audioThumb: require('../assets/screen/audioThumb.jpg'),
    customPlay: require('../assets/screen/customPlay.png'),
    send_ico: require('../assets/screen/send_ico.png'),
};

export const personalSpaceIcons =(dark=false)=>{
    return {
        myInterest: require('../assets/screen/personalSpace/myInterest.png'),
        chat: dark ? require('../assets/screen/personalSpace/1to1Dark.png') : require('../assets/screen/personalSpace/1to1Light.png'),
        invite: dark ? require('../assets/screen/personalSpace/inviteDark.png') : require('../assets/screen/personalSpace/inviteLight.png'),
    }
}
