export const light = {
    dark: false,
    colors: {
        primary: '#E2E2E2',
        primaryLine: '#E2E2E2',
        primaryDark: '#FFFFFF',
        primaryAccent: '#E0E0E0',

        collabSettingBox: '#e7fcfa',
        textInputBackground: '#E2E2E2',
        textInputDisabled: '#808080',
        textInputBorder: '#ED151F',
        warning: '#ED151F',
        lineSeparation: '#808080',
        lineSeparation2: '#a7a6a6',
        alertBox: '#FFFFFF',
        menuBox: '#FFFFFF',
        datepickerBox: '#FFFFFF',
        datepickerText: '#666666',
        datepickerCancel: '#881B7E',
        alertTitle: '#ED151F',
        dateSelection: '#ED151F',
        radiusButtons: '#881B7E',
        sliderColor: '#ED151F',
        secondaryText: '#ED1C24',
        secondaryBorder: '#ED1C24',
        RoundedButtonBackground: '#E2E2E2',
        buttonRed: '#ED151F',
        buttonPink: '#D49AA9',
        notificationListDot: '#3EBDD4',
        lovitzSender: '#ED1C24',
        lovitzReceiver: '#EAED97',
        titleSender: '#5050FF',
        titleReceiver: '#C4DFFB',
        menuDots: '#324368',
        coSpaceMenuDots: '#881B7E',
        showMore: '#edf360',
        showMoreSecondary: '#01499c',

        textPrimary: '#808080',
        textPrimaryProfile: '#000000',
        textPrimaryDark: '#666666',
        textPrimaryAccent: '#EAED97',
        link: '#2f2fc0',

        secondary: '#ED1C24',
        secondaryDark: '#ED151F',
        secondaryAccent: '#881B7E',

        collabAccent: '#B128F0',

        textSecondary: '#FFFFFF',
        textSecondaryDark: '#FFFFFF',
        textSecondaryAccent: '#F1ECEC',

        surface: '#FFFFFF',
        surfaceDark: '#FFFFFF',
        surfacePopup: '#FFFFFF',
        surfaceDarkReported: '#FFFFFF',
        surfaceAccent: '#F1ECEC',

        clipSurface: '#AF00A3',
        clipSurfaceSecondary: '#DFE2E8',
        clipSurfaceAccent: '#DD05DD',
        clipDMSecondary: '#CCEAFB',
        clipDMPrimary: '#F1ECEC',
        clipText: '#FFFFFF',
        clipTextSecondary: '#0F000E',
        searchClipSecondary: '#0F000E',
        clipTextAccent: '#EAFF74',
        clipGradiantPrimary: ['#F9FAFB', '#DFE2E8'],
        clipGradiantSecondary: ['#AF00A3', '#AF00A3'],

        customLBlue: '#3EBDD4',
        customDBlue: '#4300FF',
        customViolet: '#38446D',
        customNGreen: '#2BEB03',

        myDiaryOn: '#56FF00',
        myDiaryOff: '#9B9B9B',

        fp_surface: '#ffffff',
        fp_timer_text: '#fff',
        fp_title: '#393939',
        fp_timer: '#ed1c24',
        fp_timerMax: '#666666',
        fp_radioBtn: '#ed1c24',
        fp_radioBtnLabel: '#ed1c24',
        fp_inputBorder: '#ed1c24',
        fp_inputText: '#f47864',
        fp_inputBg: '#fef8bc',
        fp_btn: '#881b7e',
        fp_btnText: '#ffffff',
        fp_colan: '#393939',

        poll_surface: '#ffffff',
        poll_title: '#393939',
        poll_inputBg: '#fef8bc',
        poll_inputInfo: '#393939',
        poll_inputText: '#c1272d',
        poll_inputBoarder: '#c1272d',
        poll_optionBoarder1: '#a1d158',
        poll_optionBg1: '#f6ffbc',
        poll_optionBoarder2: '#acdbee',
        poll_optionBg2: '#d6efe2',
        poll_optionBoarder3: '#e1acff',
        poll_optionBg3: '#ffe1e6',
        poll_btn: '#881b7e',
        poll_btnText: '#ffffff',
        poll_preview_bg: '#efffbd',
        poll_preview_bg_border: '#cae5a6',


        lovitzRealTimeCount: '#ED151F',
        fileErrorCoSpace: '#666666',
        collabSpaceLocationOff: '#CCCCCC',
        collabSpaceLocationOn: '#00F03A',

        progressTint: "#ED151F",
        progressBackground: "#fff",
        greyScale: 'rgba(211, 209, 209, .80)',
        progressOverlay: "#f8f8ff",

        secondaryLine: "#bab6b6",
        profileOutline: '#bdbdbd',
        closeButton: '#ED151F',
        loginButtons:'#eaed97',
        loginButtonsText:'#808080',

        mostLovitzHeading:'#595757',

        titlePopupBackground:'#e5e3e3',
        titlePopupText:'#606060',

        personalSpaceButtonColor:'#d4d6d6',
        personalSpaceButtonTextColor:'#929292',

        collabSpaceTitle:'#595757',
        collabSpaceButton:'#909191',

        coSpaceButton:'#ff5c69',
        newsAndAsksButton:'#909b9b',

        inviteButton:'#D4D6D6',
        inviteButtonText:'#929292',

        chatButton:'#D4D6D6',
        chatButtonText:'#929292',

        collabingButton:'#D4D6D6',
        collabingButtonText:'#929292',

        darkModeBorder:'#606060',

        interestTagsText:'#5e5e5e',

        signupBackground:'#f9f9f9',
        signupIntroText1:'#7f7f7f',
        signupIntroText2:'#fc7b85',
        signupMapText1:'#7f7f7f',
        signupMapText2:'#fc7b85',
        signupLabelText:'#7f7f7f',
        signupInputBorder:'#727272',
        signupInputBackground:'#efefef',
        signupInputText:'#7f7f7f',
        signupCreateButton:'#808080',
        signupCreateButtonText:'#ffffff',

        appbarTitle:'#808080',
        appbarBack:'#ED151F',
    },
};

export const dark = {
    colors: {
        primary: '#1F1F1F',
        primaryLine: '#808080',
        primaryDark: '#000000',
        primaryAccent: '#3D3D3D',

        collabSettingBox: '#57575a',
        textInputBackground: '#1F1F1F',
        textInputDisabled: '#808080',
        textInputBorder: '#881B7E',
        warning: '#ED151F',
        lineSeparation: '#808080',
        lineSeparation2: '#a7a6a6',
        alertBox: '#58585A',
        menuBox: '#58585A',
        datepickerBox: '#58585A',
        datepickerText: '#FFFFFF',
        datepickerCancel: '#ab159d',
        alertTitle: '#881B7E',
        dateSelection: '#D49AA9',
        radiusButtons: '#881B7E',
        sliderColor: '#881B7E',
        secondaryText: '#D49AA9',
        secondaryBorder: '#D49AA9',
        RoundedButtonBackground: '#333333',
        buttonRed: '#ED151F',
        buttonPink: '#D49AA9',
        notificationListDot: '#3EBDD4',
        lovitzSender: '#ED1C24',
        lovitzReceiver: '#EAED97',
        titleSender: '#5050ff',
        titleReceiver: '#C4DFFB',
        menuDots: '#881B7E',
        coSpaceMenuDots: '#881B7E',
        showMore: '#edf360',
        showMoreSecondary: '#01499c',

        textPrimary: '#E2E2E2',
        textPrimaryProfile: '#FFFFFF',
        textPrimaryDark: '#FFFFFF',
        textPrimaryAccent: '#EAED97',
        link: '#2f2fc0',

        secondary: '#D49AA9',
        secondaryDark: '#D49AA9',
        secondaryAccent: '#881B7E',
        collabAccent: '#B128F0',

        textSecondary: '#E0E0E0',
        textSecondaryDark: '#FFFFFF',
        textSecondaryAccent: '#F1ECEC',

        surface: 'rgb(40,40,40)',
        surfaceDark: 'rgb(30,30,30)',
        surfacePopup: 'rgb(80,80,80)',
        surfaceDarkReported: 'rgb(80,80,80)',
        surfaceAccent: 'rgb(40,40,40)',

        clipSurface: '#AF00A3',
        clipSurfaceSecondary: '#DFE2E8',
        clipSurfaceAccent: '#DD05DD',
        clipDMSecondary: '#CCEAFB',
        clipDMPrimary: '#F1ECEC',
        clipText: '#FFFFFF',
        clipTextSecondary: '#0F000E',
        searchClipSecondary: '#FFFFFF',
        clipTextAccent: '#EAFF74',
        clipGradiantPrimary: ['#F9FAFB', '#DFE2E8'],
        clipGradiantSecondary: ['#AF00A3', '#AF00A3'],

        customLBlue: '#3EBDD4',
        customDBlue: '#4300FF',
        customViolet: '#38446D',
        customNGreen: '#2BEB03',

        myDiaryOn: '#56FF00',
        myDiaryOff: '#9B9B9B',

        fp_surface: '#808080',
        fp_timer_text: '#fff',
        fp_title: '#ffffff',
        fp_timer: '#fcee21',
        fp_timerMax: '#ffffff',
        fp_radioBtn: '#ff90a8',
        fp_radioBtnLabel: '#ffffff',
        fp_inputBorder: '#ed1c24',
        fp_inputText: '#f47864',
        fp_inputBg: '#fef8bc',
        fp_btn: '#881b7e',
        fp_btnText: '#ffffff',
        fp_colan: '#393939',

        poll_surface: '#808080',
        poll_title: '#ffffff',
        poll_inputBg: '#fef8bc',
        poll_inputInfo: '#393939',
        poll_inputText: '#c1272d',
        poll_inputBoarder: '#c1272d',
        poll_optionBoarder1: '#a1d158',
        poll_optionBg1: '#f6ffbc',
        poll_optionBoarder2: '#acdbee',
        poll_optionBg2: '#d6efe2',
        poll_optionBoarder3: '#e1acff',
        poll_optionBg3: '#ffe1e6',
        poll_btn: '#881b7e',
        poll_btnText: '#ffffff',
        poll_preview_bg: '#efffbd',
        poll_preview_bg_border: '#cae5a6',


        lovitzRealTimeCount: '#FF90A8',
        fileErrorCoSpace: '#666666',
        collabSpaceLocationOff: '#CCCCCC',
        collabSpaceLocationOn: '#00F03A',

        progressTint: "#ED151F",
        progressBackground: "#fff",
        greyScale: 'rgba(211, 209, 209, .80)',
        progressOverlay: "#f8f8ff",
        secondaryLine: "#bab6b6",
        profileOutline: '#bdbdbd',
        closeButton: '#ED151F',
        loginButtons:'#D8D6D6',
        loginButtonsText:'#808080',

        mostLovitzHeading:'#fffdfd',

        titlePopupBackground:'#e5e3e3',
        titlePopupText:'#606060',


        personalSpaceButtonColor:'#d4d6d6',
        personalSpaceButtonTextColor:'#929292',

        collabSpaceTitle:'#fffdfd',
        collabSpaceButton:'#000000',

        coSpaceButton:'#000000',
        newsAndAsksButton:'#000000',

        inviteButton:'#000000',
        inviteButtonText:'#929292',

        chatButton:'#000000',
        chatButtonText:'#929292',

        collabingButton:'#000000',
        collabingButtonText:'#929292',

        darkModeBorder:'#606060',

        interestTagsText:'#bcbcbc',


        signupBackground:'#000000',
        signupIntroText1:'#7f7f7f',
        signupIntroText2:'#fc7b85',
        signupMapText1:'#7f7f7f',
        signupMapText2:'#fc7b85',
        signupLabelText:'#7f7f7f',
        signupInputBorder:'#727272',
        signupInputBackground:'#efefef',
        signupInputText:'#7f7f7f',
        signupCreateButton:'#808080',
        signupCreateButtonText:'#ffffff',

        appbarTitle:'#808080',
        appbarBack:'#D49AA9',
    },
    dark: true,
};

const theme = {light, dark};
export default theme;
