import {Platform, StyleSheet} from 'react-native';
import scale from '../../utilities/scale';

export default function imagePickerStyle({colors}) {
    return StyleSheet.create({
        image: {
            width: '100%',
            height: '100%',
        },
        imageBlock: {
            flex: 2,
            flexDirection: 'row',
            width: '100%',
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 20,
        },
        activityIndicator: {
            position: 'absolute',
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
        },
        imageContainer: {
            shadowColor: '#006',
            marginTop: 20,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            borderRadius: 50,
            padding: 2,
            shadowOpacity: Platform.OS === 'ios' ? 0 : 10,
        },
        closeIcon: {
            width: scale.icon.xl,
            height: scale.icon.xl,
            tintColor: colors.secondaryDark,
            margin: scale.space.s,
        },
        addButton: {
            position: 'absolute',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#f8f8ff',
            opacity: 0.8,
            zIndex: 2,
            width: 30,
            height: 30,
            right: 0,
            bottom: 0,
            borderRadius: 50,
        },
        loadingBG: {
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: colors.surfaceAccent,
            opacity: 0.8,
            zIndex: 2,
            width: 20,
            height: 20,
            borderRadius: 50,
        },

        container: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#fff',
        },
        logo: {
            width: 200,
            height: 200,
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 20,
            marginTop: -100,
        },
        logoImage: {
            width: '100%',
            height: '100%',
            resizeMode: 'contain',
        },
        title: {
            fontSize: scale.font.xxxl,
            color: '#305fb4',
            marginTop: 20,
            marginBottom: 20,
            textAlign: 'center',
        },
        loginContainer: {
            width: '70%',
            backgroundColor: '#305fb4',
            borderRadius: 25,
            padding: 10,
            marginTop: 30,
            alignSelf: 'center',
            justifyContent: 'center',
            height: 48,
        },
        loginText: {
            color: '#fff',
        },
        signupContainer: {
            justifyContent: 'center',
            width: '70%',
            backgroundColor: '#FFF',
            borderRadius: 25,
            borderWidth: Platform.OS === 'ios' ? 0.5 : 1.0,
            borderColor: '#305fb4',
            padding: 10,
            marginTop: 20,
            alignSelf: 'center',
            height: 45,
        },
        signupText: {
            color: '#305fb4',
        },
        lineStyle: {
            flex: 1,
            borderWidth: 0.5,
            borderColor: 'black',
            alignSelf: 'stretch',
        },
        leftLine: {
            marginEnd: 5,
            marginStart: 10,
            marginTop: 10,
            marginBottom: 10,
        },
        socialButton: {
            alignSelf: 'center',
            width: 40,
            height: 40,
            resizeMode: 'contain',
        },
        backgroundImageStyle: {
            flex: 1,
            // marginTop:160,
            // transform : [ { scaleX : 2 } ],
            // borderTopLeftRadius : 200,
            // borderTopRightRadius : 200,
            alignSelf: 'center',
            width: '100%',
        },
        logoContainer: {
            backgroundColor: '#fff',
            // marginTop:160,
            height: 130,
            marginBottom: 15,
            transform: [{scaleX: 1.8}],
            borderBottomLeftRadius: 200,
            borderBottomRightRadius: 200,
        },
        rightLine: {
            marginStart: 5,
            marginEnd: 10,
            marginTop: 10,
            marginBottom: 10,
        },
        input: {
            height: 48,
            borderRadius: 25,
            overflow: 'hidden',
            backgroundColor: 'white',
            borderWidth: 1,
            borderColor: '#d91b3e',
            marginTop: 10,
            marginBottom: 10,
            marginLeft: 30,
            marginRight: 30,
            paddingLeft: 16,
        },
        button: {
            backgroundColor: '#b71c1c',
            marginLeft: 30,
            marginRight: 30,
            marginTop: 5,
            height: 48,
            borderRadius: 5,
            alignItems: 'center',
            justifyContent: 'center',
        },
        buttonTitle: {
            color: 'white',
            fontSize: scale.font.xl,
        },
        footerView: {
            flex: 1,
            alignItems: 'center',
            marginTop: 20,
            marginBottom: 20,
        },
        footerText: {
            fontSize: scale.font.xl,
            color: '#2e2e2d',
        },
        footerLink: {
            color: '#b71c1c',
            fontSize: scale.font.xl,
        },
        resetText: {
            fontSize: scale.font.s,
            color: '#2e2e2d',
        },
        resetLink: {
            color: '#b71c1c',
            fontSize: scale.font.s,
        },
    });
}
